
interface NDArrayInt32 {
  void NDArrayInt32(
    unsigned long[] shape,
    unsigned long shape_len);

  long get(
    long[] index, long index_len);

  void set(
    long[] index, long index_len, long value);

};

interface NDArrayFloat32 {
  void NDArrayFloat32(
    unsigned long[] shape,
    unsigned long shape_len);

  float get(
    long[] index, long index_len);

  void set(
    long[] index, long index_len, float value);
};
